/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TrainerRouteImport } from './routes/trainer'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminAppointmentsRouteImport } from './routes/admin.appointments'
import { Route as AdminAttendanceRouteImport } from './routes/admin.attendance'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminTrainersRouteImport } from './routes/admin.trainers'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as MemberBookRouteImport } from './routes/member.book'
import { Route as MemberBookingsRouteImport } from './routes/member.bookings'
import { Route as MemberNotificationsRouteImport } from './routes/member.notifications'
import { Route as MemberPlansRouteImport } from './routes/member.plans'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberQrRouteImport } from './routes/member.qr'
import { Route as TrainerIndexRouteImport } from './routes/trainer.index'
import { Route as TrainerAppointmentsRouteImport } from './routes/trainer.appointments'
import { Route as TrainerAvailabilityRouteImport } from './routes/trainer.availability'
import { Route as TrainerMembersRouteImport } from './routes/trainer.members'
import { Route as TrainerMessagesRouteImport } from './routes/trainer.messages'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainerRoute = TrainerRouteImport.update({
  id: '/trainer',
  path: '/trainer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceRoute = AdminAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTrainersRoute = AdminTrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => AdminRoute,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBookRoute = MemberBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBookingsRoute = MemberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MemberRoute,
} as any)
const MemberNotificationsRoute = MemberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MemberRoute,
} as any)
const MemberPlansRoute = MemberPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberQrRoute = MemberQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MemberRoute,
} as any)
const TrainerIndexRoute = TrainerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAppointmentsRoute = TrainerAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerAvailabilityRoute = TrainerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerMembersRoute = TrainerMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => TrainerRoute,
} as any)
const TrainerMessagesRoute = TrainerMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TrainerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/member/book': typeof MemberBookRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/plans': typeof MemberPlansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/trainer/appointments': typeof TrainerAppointmentsRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/members': typeof TrainerMembersRoute
  '/trainer/messages': typeof TrainerMessagesRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/member/book': typeof MemberBookRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/plans': typeof MemberPlansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/trainer/appointments': typeof TrainerAppointmentsRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/members': typeof TrainerMembersRoute
  '/trainer/messages': typeof TrainerMessagesRoute
  '/admin': typeof AdminIndexRoute
  '/member': typeof MemberIndexRoute
  '/trainer': typeof TrainerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/signup': typeof SignupRoute
  '/trainer': typeof TrainerRouteWithChildren
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/attendance': typeof AdminAttendanceRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/trainers': typeof AdminTrainersRoute
  '/member/book': typeof MemberBookRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/plans': typeof MemberPlansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/trainer/appointments': typeof TrainerAppointmentsRoute
  '/trainer/availability': typeof TrainerAvailabilityRoute
  '/trainer/members': typeof TrainerMembersRoute
  '/trainer/messages': typeof TrainerMessagesRoute
  '/admin/': typeof AdminIndexRoute
  '/member/': typeof MemberIndexRoute
  '/trainer/': typeof TrainerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/member'
    | '/signup'
    | '/trainer'
    | '/admin/announcements'
    | '/admin/appointments'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/plans'
    | '/admin/reports'
    | '/admin/trainers'
    | '/member/book'
    | '/member/bookings'
    | '/member/notifications'
    | '/member/plans'
    | '/member/profile'
    | '/member/qr'
    | '/trainer/appointments'
    | '/trainer/availability'
    | '/trainer/members'
    | '/trainer/messages'
    | '/admin/'
    | '/member/'
    | '/trainer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/announcements'
    | '/admin/appointments'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/plans'
    | '/admin/reports'
    | '/admin/trainers'
    | '/member/book'
    | '/member/bookings'
    | '/member/notifications'
    | '/member/plans'
    | '/member/profile'
    | '/member/qr'
    | '/trainer/appointments'
    | '/trainer/availability'
    | '/trainer/members'
    | '/trainer/messages'
    | '/admin'
    | '/member'
    | '/trainer'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/member'
    | '/signup'
    | '/trainer'
    | '/admin/announcements'
    | '/admin/appointments'
    | '/admin/attendance'
    | '/admin/members'
    | '/admin/plans'
    | '/admin/reports'
    | '/admin/trainers'
    | '/member/book'
    | '/member/bookings'
    | '/member/notifications'
    | '/member/plans'
    | '/member/profile'
    | '/member/qr'
    | '/trainer/appointments'
    | '/trainer/availability'
    | '/trainer/members'
    | '/trainer/messages'
    | '/admin/'
    | '/member/'
    | '/trainer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  SignupRoute: typeof SignupRoute
  TrainerRoute: typeof TrainerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainer': {
      id: '/trainer'
      path: '/trainer'
      fullPath: '/trainer'
      preLoaderRoute: typeof TrainerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance': {
      id: '/admin/attendance'
      path: '/attendance'
      fullPath: '/admin/attendance'
      preLoaderRoute: typeof AdminAttendanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/trainers': {
      id: '/admin/trainers'
      path: '/trainers'
      fullPath: '/admin/trainers'
      preLoaderRoute: typeof AdminTrainersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/book': {
      id: '/member/book'
      path: '/book'
      fullPath: '/member/book'
      preLoaderRoute: typeof MemberBookRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/bookings': {
      id: '/member/bookings'
      path: '/bookings'
      fullPath: '/member/bookings'
      preLoaderRoute: typeof MemberBookingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/notifications': {
      id: '/member/notifications'
      path: '/notifications'
      fullPath: '/member/notifications'
      preLoaderRoute: typeof MemberNotificationsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/plans': {
      id: '/member/plans'
      path: '/plans'
      fullPath: '/member/plans'
      preLoaderRoute: typeof MemberPlansRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/qr': {
      id: '/member/qr'
      path: '/qr'
      fullPath: '/member/qr'
      preLoaderRoute: typeof MemberQrRouteImport
      parentRoute: typeof MemberRoute
    }
    '/trainer/': {
      id: '/trainer/'
      path: '/'
      fullPath: '/trainer/'
      preLoaderRoute: typeof TrainerIndexRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/appointments': {
      id: '/trainer/appointments'
      path: '/appointments'
      fullPath: '/trainer/appointments'
      preLoaderRoute: typeof TrainerAppointmentsRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/availability': {
      id: '/trainer/availability'
      path: '/availability'
      fullPath: '/trainer/availability'
      preLoaderRoute: typeof TrainerAvailabilityRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/members': {
      id: '/trainer/members'
      path: '/members'
      fullPath: '/trainer/members'
      preLoaderRoute: typeof TrainerMembersRouteImport
      parentRoute: typeof TrainerRoute
    }
    '/trainer/messages': {
      id: '/trainer/messages'
      path: '/messages'
      fullPath: '/trainer/messages'
      preLoaderRoute: typeof TrainerMessagesRouteImport
      parentRoute: typeof TrainerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminAttendanceRoute: typeof AdminAttendanceRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTrainersRoute: typeof AdminTrainersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminAttendanceRoute: AdminAttendanceRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTrainersRoute: AdminTrainersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MemberRouteChildren {
  MemberBookRoute: typeof MemberBookRoute
  MemberBookingsRoute: typeof MemberBookingsRoute
  MemberNotificationsRoute: typeof MemberNotificationsRoute
  MemberPlansRoute: typeof MemberPlansRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberQrRoute: typeof MemberQrRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberBookRoute: MemberBookRoute,
  MemberBookingsRoute: MemberBookingsRoute,
  MemberNotificationsRoute: MemberNotificationsRoute,
  MemberPlansRoute: MemberPlansRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberQrRoute: MemberQrRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

interface TrainerRouteChildren {
  TrainerAppointmentsRoute: typeof TrainerAppointmentsRoute
  TrainerAvailabilityRoute: typeof TrainerAvailabilityRoute
  TrainerMembersRoute: typeof TrainerMembersRoute
  TrainerMessagesRoute: typeof TrainerMessagesRoute
  TrainerIndexRoute: typeof TrainerIndexRoute
}

const TrainerRouteChildren: TrainerRouteChildren = {
  TrainerAppointmentsRoute: TrainerAppointmentsRoute,
  TrainerAvailabilityRoute: TrainerAvailabilityRoute,
  TrainerMembersRoute: TrainerMembersRoute,
  TrainerMessagesRoute: TrainerMessagesRoute,
  TrainerIndexRoute: TrainerIndexRoute,
}

const TrainerRouteWithChildren =
  TrainerRoute._addFileChildren(TrainerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  SignupRoute: SignupRoute,
  TrainerRoute: TrainerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
