/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberRouteImport } from './routes/member'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MemberIndexRouteImport } from './routes/member.index'
import { Route as MemberBookRouteImport } from './routes/member.book'
import { Route as MemberBookingsRouteImport } from './routes/member.bookings'
import { Route as MemberNotificationsRouteImport } from './routes/member.notifications'
import { Route as MemberPlansRouteImport } from './routes/member.plans'
import { Route as MemberProfileRouteImport } from './routes/member.profile'
import { Route as MemberQrRouteImport } from './routes/member.qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberRoute = MemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberIndexRoute = MemberIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBookRoute = MemberBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => MemberRoute,
} as any)
const MemberBookingsRoute = MemberBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => MemberRoute,
} as any)
const MemberNotificationsRoute = MemberNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MemberRoute,
} as any)
const MemberPlansRoute = MemberPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => MemberRoute,
} as any)
const MemberProfileRoute = MemberProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MemberRoute,
} as any)
const MemberQrRoute = MemberQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MemberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/signup': typeof SignupRoute
  '/member/book': typeof MemberBookRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/plans': typeof MemberPlansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/member/book': typeof MemberBookRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/plans': typeof MemberPlansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/member': typeof MemberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/member': typeof MemberRouteWithChildren
  '/signup': typeof SignupRoute
  '/member/book': typeof MemberBookRoute
  '/member/bookings': typeof MemberBookingsRoute
  '/member/notifications': typeof MemberNotificationsRoute
  '/member/plans': typeof MemberPlansRoute
  '/member/profile': typeof MemberProfileRoute
  '/member/qr': typeof MemberQrRoute
  '/member/': typeof MemberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/member'
    | '/signup'
    | '/member/book'
    | '/member/bookings'
    | '/member/notifications'
    | '/member/plans'
    | '/member/profile'
    | '/member/qr'
    | '/member/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/member/book'
    | '/member/bookings'
    | '/member/notifications'
    | '/member/plans'
    | '/member/profile'
    | '/member/qr'
    | '/member'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/member'
    | '/signup'
    | '/member/book'
    | '/member/bookings'
    | '/member/notifications'
    | '/member/plans'
    | '/member/profile'
    | '/member/qr'
    | '/member/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MemberRoute: typeof MemberRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member': {
      id: '/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof MemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member/': {
      id: '/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof MemberIndexRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/book': {
      id: '/member/book'
      path: '/book'
      fullPath: '/member/book'
      preLoaderRoute: typeof MemberBookRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/bookings': {
      id: '/member/bookings'
      path: '/bookings'
      fullPath: '/member/bookings'
      preLoaderRoute: typeof MemberBookingsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/notifications': {
      id: '/member/notifications'
      path: '/notifications'
      fullPath: '/member/notifications'
      preLoaderRoute: typeof MemberNotificationsRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/plans': {
      id: '/member/plans'
      path: '/plans'
      fullPath: '/member/plans'
      preLoaderRoute: typeof MemberPlansRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/profile': {
      id: '/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof MemberProfileRouteImport
      parentRoute: typeof MemberRoute
    }
    '/member/qr': {
      id: '/member/qr'
      path: '/qr'
      fullPath: '/member/qr'
      preLoaderRoute: typeof MemberQrRouteImport
      parentRoute: typeof MemberRoute
    }
  }
}

interface MemberRouteChildren {
  MemberBookRoute: typeof MemberBookRoute
  MemberBookingsRoute: typeof MemberBookingsRoute
  MemberNotificationsRoute: typeof MemberNotificationsRoute
  MemberPlansRoute: typeof MemberPlansRoute
  MemberProfileRoute: typeof MemberProfileRoute
  MemberQrRoute: typeof MemberQrRoute
  MemberIndexRoute: typeof MemberIndexRoute
}

const MemberRouteChildren: MemberRouteChildren = {
  MemberBookRoute: MemberBookRoute,
  MemberBookingsRoute: MemberBookingsRoute,
  MemberNotificationsRoute: MemberNotificationsRoute,
  MemberPlansRoute: MemberPlansRoute,
  MemberProfileRoute: MemberProfileRoute,
  MemberQrRoute: MemberQrRoute,
  MemberIndexRoute: MemberIndexRoute,
}

const MemberRouteWithChildren =
  MemberRoute._addFileChildren(MemberRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MemberRoute: MemberRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
